  [[main]]
  name = "TRANG CHỦ"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "BÀI VIẾT"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "DỰ ÁN"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "GIỚI THIỆU VỀ TÔI"
  weight = 400
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "THÀNH TỰU"
  weight = 500
  identifier = "accomplishments"

  [[main]]
  name = "GIẢI THƯỞNG"
  weight = 510
  identifier = "awards"
  url = "/awards/"
  parent = "accomplishments"  

  [[main]]
  name = "CHỨNG CHỉ"
  weight = 520
  identifier = "certifications"
  url = "/certifications/"
  parent = "accomplishments"

  [[main]]
  name = "Liên hệ"
  weight = 600
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"